version: '3.8'
services:
  back-end:
    container_name: back-end
    build:
      context: back-end
    ports:
      - "80:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      SIGNATURE_TYPE: RSA
      BANK_NAME: "Bankit!"
      BANK_ID: "RSA"
    depends_on:
      - db
    volumes:
      - ./back-end:/usr/src/back-end
      - /usr/src/back-end/node_modules # Để tránh lỗi `node_modules` bị ghi đè
  db:
    container_name: db
    image: postgres
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # front-end:
  #   container_name: front-end
  #   build:
  #     context: front-end
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - back-end
  #   volumes:
  #     - ./front-end:/usr/src/front-end
  #     - /usr/src/front-end/node_modules # Để tránh lỗi `node_modules` bị ghi đè

volumes:
  postgres-data:
    driver: local
