version: '3.8'
services:
  back-end:
    container_name: back-end
    build:
      context: back-end
    ports:
      - "80:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
